feat(connector-besu): remove hard dependency on keychain
hyperledger/cacti pull request #1536
Opened 2021-11-12 17:20 UTC by TonyRowntree

Removed the hard dependency on keychain for connector-besu.

**Added:** 
- getContractInfo method for keychain and JsonObject.
- invokeContractPrivateTx method for private transactions.
- New tests for deploying and invoking the contract using JSON object.

**Updated:** 

- invokeContract method to handle the new getContract methods.
- Tests to use new methods.

Resolves #1163 

Signed-off-by: TonyRowntree <33454202+TonyRowntree@users.noreply.github.com>

2021-11-15 15:22 UTC, takeutak approved these changes

2021-11-23 03:12 UTC, petermetz requested changes

2021-11-23 03:12 UTC, petermetz commented on packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/invoke-contract-endpoint.ts
> +      const resBody = await this.options.connector.getContractInfoKeychain(
@TonyRowntree Based on the method name getContractInfoKeychain I would conclude that the invoke contract endpoint does not do any contract invocation. Does it actually do contract invocation? If yes it definitely needs a name that implies that.

2021-11-23 03:12 UTC, petermetz commented on packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
> +                    "contractName": {
@TonyRowntree Is `contractName` being used anywhere in the plugin's method that uses this request object? I couldn't find it.

2021-11-23 03:12 UTC, petermetz commented on packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
> +                    "contractAbi": {
@TonyRowntree Is `contractAbi` being used anywhere in the plugin's method that uses this request object? I couldn't find it.

2021-11-23 03:13 UTC, petermetz requested changes
@TonyRowntree The PR description would be a much nicer commit message as well. Right now the commit message is:

```sh
feat(connector-besu): remove hard dependency on keychain 

Signed-off-by: TonyRowntree <33454202+TonyRowntree@users.noreply.github.com>

feat(conn): squashclear

Signed-off-by: TonyRowntree <33454202+TonyRowntree@users.noreply.github.com>

feat(connector-besu): squashnode

Signed-off-by: TonyRowntree <33454202+TonyRowntree@users.noreply.github.com>

feat(connector-besu): squash!!!

Signed-off-by: TonyRowntree <33454202+TonyRowntree@users.noreply.github.com>

fix: squashgit rebase upstream/main

Signed-off-by: TonyRowntree <33454202+TonyRowntree@users.noreply.github.com>
```

2022-05-16 05:51 UTC, jagpreetsinghsasan commented
Hi @TonyRowntree 
Any updates on this?

2023-08-17 01:38 UTC, petermetz commented
Closing for now as part of the tidying up of the PR backlog. Feel free to re-open anytime!

2023-08-17 01:38 UTC, closed without merging