refactor(cmd-api-server): clean up configuration parameters gitguardi…
hyperledger/cacti pull request #2086
Opened 2022-06-20 06:31 UTC by ruzell22

…an scanner test

test

Signed-off-by: ruzell22 <ruzell.vince.aquino@accenture.com>

2023-02-16 01:49 UTC, petermetz commented on .github/workflows/gg-shield-action.yaml
> +          args: --show-secrets --exit-zero --all-policies --verbose
```suggestion
args: --show-secrets --exit-zero --all-policies --verbose --config-path ./gitguardian.yaml
```

2023-02-16 01:51 UTC, petermetz requested changes
@ruzell22 Please check out my suggestions here: https://github.com/hyperledger/cacti/pull/2086/files#r1107923389

2023-02-16 01:59 UTC, petermetz requested changes
@ruzell22 Final change request and sorry for spamming: Please break this into two pull requests where:
1. First PR is just about adding the custom git guardian check of ours (e.g. the gitguardian workflow + the configuration file) - this PR must also address the change requests I just added related to the git guardian config files and workflow file
2. Second PR is one that you mark as dependent on the first PR and it does the originally intended change which was to clean up the configuration parameters.

2023-02-16 01:59 UTC, petermetz commented on .github/workflows/gg-shield-action.yaml
> +          GITHUB_TOKEN: "87028c11-8bef-4bd6-b440-5d3851314ead"
@ruzell22 Please remove this and make sure to invalidate your token because this one now has been exposed.

2023-02-16 01:59 UTC, petermetz commented on .github/workflows/gg-shield-action.yaml
> +        uses: GitGuardian/ggshield-action@master
@ruzell22 Please pin to a specific version (whichever is latest right now is fine but it has to be a specific version such as v.3.2.1)

2023-02-16 01:59 UTC, petermetz commented on .github/workflows/gg-shield-action.yaml
> +          GITGUARDIAN_INSTANCE: 'https://api.gitguardian.com/'
@ruzell22 Please double check if we need this (e.g. remove them and then see if the checking process still works or not). If it does work without these then they should be removed. If it does NOT work without these then we MUST:
1. Invalidate this gitguardian API key before someone maliciously uses it
2. Generate a new git guardian API key, send that to me in private and I'll make sure to add it as a git repo level environment secret.

2023-08-17 23:39 UTC, petermetz commented
@ruzell22 Are you still working on this?

2023-08-22 00:19 UTC, ruzell22 commented
Hello @petermetz , the clean up configuration part is fixed already. However, the gitguardian issue is yet to be resolved. The question has been posted at stackoverflow, thank you.

2023-08-29 07:52 UTC, ruzell22 commented
Hello @petermetz , this draft PR relating to gitguardian can now be closed. Thank you.

2023-08-29 23:01 UTC, petermetz commented
> Hello @petermetz , this draft PR relating to gitguardian can now be closed. Thank you.

@ruzell22 Got it, closing, thank you as well!

2023-08-29 23:01 UTC, closed without merging