fix(security): vulnerabilities found in fabric-all-in-one
hyperledger/cacti pull request #2121
Opened 2022-07-19 06:44 UTC by zondervancalvez

Fixes #2056

2022-07-20 05:51 UTC, jagpreetsinghsasan commented
Thanks for the contribution. This looks more likely a nice to have sort of thing, rather than a vulnerability fix as we dont call the AIO images as production ready, those are just for testing purposes. But yes, still the base image change is a good update.

2022-07-20 05:52 UTC, jagpreetsinghsasan approved these changes

2022-07-20 19:36 UTC, takeutak approved these changes

2022-07-23 00:15 UTC, petermetz approved these changes
@zondervancalvez LGTM, thank you!

2022-08-17 06:55 UTC, zondervancalvez commented
@izuru0 @sanvenDev following up for your review. Thank you.

2022-08-26 08:28 UTC, petermetz requested changes
@zondervancalvez Please fix the DCO

2022-09-01 14:18 UTC, zondervancalvez commented
@petermetz DCO is now fixed

2023-04-02 17:21 UTC, merged