fix(security): vulnerabilities found in quorum-multi-party-all-in-one
hyperledger/cacti pull request #2239
Opened 2022-12-23 09:36 UTC by aldousalvarez

Fixes #2060

Signed-off-by: aldousalvarez <aldousss.alvarez@gmail.com>

2022-12-23 09:38 UTC, aldousalvarez commented
Hello @petermetz , Most of the vulnerabilities are now fixed in quorum-multi-party-all-in-one but there are still some that are not because most of the remaining vulnerabilities are still new and is still waiting for the new changes to be pulled in and released on their respective package versions. And we tried to ask on the quorum discussions on github as you can see here. (https://github.com/ConsenSys/quorum/discussions/1513).

Here are the remaining vulnerabilities for quorum-multi-party-all-in-one:
CVE-2022-24713
CVE-2021-41092
CVE-2022-27664
CVE-2022-32149
CVE-2021-41092 
CVE-2022-32149

2022-12-24 18:28 UTC, petermetz requested changes

2022-12-24 18:28 UTC, petermetz commented on .github/containerscan/allowedlist.yaml
> +    - CVE-2022-32149
@aldousalvarez Same here as with the other quorum image PR: I would remove these from the ignored CVEs for now unless we have a strong reason to not to.

2023-01-11 04:45 UTC, aldousalvarez commented on .github/containerscan/allowedlist.yaml
> +    - CVE-2022-32149
Noted on that. Thank you, already fixed it

2023-01-25 04:38 UTC, petermetz commented on .github/containerscan/allowedlist.yaml
> +    - CVE-2022-32149
@aldousalvarez Great, thanks for the updates!

2023-01-25 04:38 UTC, petermetz approved these changes
@aldousalvarez LGTM, thank you!

2023-01-27 05:44 UTC, jagpreetsinghsasan approved these changes
LGTM, thankyou!

2023-01-30 00:45 UTC, petermetz commented
Removing my approval so that we don't accidentally merge before someone else also approves.

2023-03-28 03:17 UTC, takeutak approved these changes

2023-03-28 03:21 UTC, petermetz approved these changes
LGTM

2023-04-01 23:38 UTC, merged