fix(security): vulnerabilities found in quorum-all-in-one
hyperledger/cacti pull request #2240
Opened 2022-12-23 09:57 UTC by aldousalvarez

Fixes #2059

Signed-off-by: aldousalvarez <aldousss.alvarez@gmail.com>

2022-12-23 09:58 UTC, aldousalvarez commented
Hello @petermetz , Most of the vulnerabilities are now fixed in quorum-all-in-one but there are still some that are not because most of the remaining vulnerabilities are still new and is still waiting for the new changes to be pulled in and released on their respective package versions. And we tried to ask on the quorum discussions on github as you can see here. (https://github.com/ConsenSys/quorum/discussions/1513).

Here are the remaining vulnerabilities for [quorum-all-in-one](https://github.com/hyperledger/cactus/actions/runs/3728650724/jobs/6323849770): 
CVE-2022-3602
CVE-2022-3786
CVE-2022-3602
CVE-2022-3786
CVE-2022-42003
CVE-2022-42004
CVE-2022-45868
CVE-2022-1471
CVE-2022-21698
CVE-2022-27664
CVE-2022-32149
CVE-2022-21698
CVE-2022-27664
CVE-2022-32149

2022-12-24 04:36 UTC, petermetz requested changes
@aldousalvarez Please fix the container build, right now it's broken.

2023-01-11 04:44 UTC, aldousalvarez commented
Fixed the container build and is now passing

2023-03-27 00:38 UTC, petermetz approved these changes
@aldousalvarez Thank you, LGTM

2023-04-06 14:42 UTC, takeutak approved these changes

2023-04-07 00:17 UTC, merged