fix(security): vulnerabilities found in cactus-connector-besu
hyperledger/cacti pull request #2241
Opened 2022-12-23 10:11 UTC by aldousalvarez

Fixes #2040

Signed-off-by: aldousalvarez <aldousss.alvarez@gmail.com>

2022-12-23 10:12 UTC, aldousalvarez commented
Hello Peter, Most of the vulnerabilities are now fixed in cactus-plugin-ledger-connector-besu but there are still some that is not yet fixed as you can see [here](https://github.com/hyperledger/cactus/actions/runs/3728650724/jobs/6323849013
). The only vulnerability (CVE-2022-2421) is still a vulnerability because the latest version of the package that is being used is still the affected version. The changes committed on this PR will fix the 3 out of the 4  remaining vulnerabilities (CVE-2022-24434, CVE-2022-24999, and CVE-2022-24999) once the changes are applied and the new version is released and the packages are updated just like the v1.1 release.

2022-12-24 18:31 UTC, petermetz requested changes
@aldousalvarez A dozen or so packages have their tests failing so I'm thinking this is probably not a flake but an actual regression. Please fix and then pass it back for review once the tests are passing.

2022-12-24 18:31 UTC, petermetz commented on .github/containerscan/allowedlist.yaml
> +    - CVE-2022-2421
@aldousalvarez I'd prefer to leave this out, unless there's a specific reason to ignore these CVEs.

2023-01-11 04:44 UTC, aldousalvarez commented on .github/containerscan/allowedlist.yaml
> +    - CVE-2022-2421
Noted on this, thank you. I already fixed it.

2023-03-27 16:53 UTC, petermetz requested changes
@aldousalvarez Same here as with the other vulnerability fix PR Of yours, please clarify the CVE ID in the commit subject and PR title and then we should be good to go.

2023-03-29 03:32 UTC, aldousalvarez commented
Hello @petermetz already updated the commit subject and PR title as to your requested changes. Thank you.

2023-03-29 04:51 UTC, petermetz approved these changes
@aldousalvarez Thank you for the updates, LGTM!

2023-04-05 10:53 UTC, aldousalvarez commented
Hello @petermetz, After rebasing with the latest commit I have seen that my initial commit was already fixed by the new commits that has been merged so I have no more changes that can be applied. 


Initial Commit
https://github.com/hyperledger/cacti/commit/ce63556c69df7fada460d8972b4ce9f9c1d71a68


Merged Commits:
https://github.com/hyperledger/cacti/commit/d28d5e8f3ed5dff1aa049c8f1bccce79aa21e948
https://github.com/hyperledger/cacti/commit/1cc9667e2432d1d27c2647b86e42707a2e78e4c3

2023-04-12 01:05 UTC, closed without merging