fix(security): vulnerabilities found in cactus-example-supply-chain-app
hyperledger/cacti pull request #2242
Opened 2022-12-23 10:42 UTC by aldousalvarez

Fixes #2041

Signed-off-by: aldousalvarez <aldousss.alvarez@gmail.com>

2022-12-23 10:44 UTC, aldousalvarez commented
Hello Peter, Most of the vulnerabilities are now fixed in cactus-example-supply-chain-app but there are still some that is not yet fixed as you can see [here](https://github.com/hyperledger/cactus/actions/runs/3728650724/jobs/6323849435
). The only vulnerability (CVE-2022-2421) is still a vulnerability because the latest version of the package that is being used is still the affected version. The changes committed on this PR will fix the 3 out of the 4  remaining vulnerabilities (CVE-2022-24434, CVE-2022-24999, and CVE-2022-24999) once the changes are applied and the new version is released and the packages are updated just like the v1.1 release.

2022-12-24 04:33 UTC, petermetz requested changes

2022-12-24 04:33 UTC, petermetz commented on .github/containerscan/allowedlist.yaml
> +    - CVE-2022-2421
@aldousalvarez Let's just leave these out for now, as-in, revert the changes in allowedlist.yaml 'coz I think we can find some way to fix those vulnerabilities and in the meantime they shouldn't be masked unless absolutely necessary.
Other than this, it LGTM

2023-01-04 07:58 UTC, izuru0 approved these changes
LGTM

2023-01-11 04:43 UTC, aldousalvarez commented on .github/containerscan/allowedlist.yaml
> +    - CVE-2022-2421
Okay Thank you, noted on that one. Already fixed it.

2023-03-27 16:51 UTC, petermetz approved these changes
@aldousalvarez LGTM, thank you!

2023-03-27 16:52 UTC, petermetz requested changes
@aldousalvarez Sorry, my bad, I do need to ask that you put CVE IDs in the commit subject so that it's unique across the commit log. Other than that, we are good to go.

2023-03-29 03:32 UTC, aldousalvarez commented
Hello @petermetz also updated the commit subject and PR title as from your requested changes on this one. Thank you.

2023-03-29 04:50 UTC, petermetz approved these changes
@aldousalvarez Great, thank you for the updates, LGTM!

2023-04-02 23:17 UTC, merged