fabric-watch-blocks-v1-endpoint.test.ts fix var names
hyperledger/cacti pull request #2286
Opened 2023-02-09 16:34 UTC by barneyshyperethers

in plugin connector fabric changes names of variables , some minor change It is not critical change.

barnaba.pawelczak@fujitsu.com

Signed-off-by: barneyshyperethers <109078012+barneyshyperethers@users.noreply.github.com>

2023-02-10 07:38 UTC, jagpreetsinghsasan commented
Hi @barneyshyperethers 
Thankyou for the pull request. Please fix the PR commit message to a more standard one (you can refer to previously merged PRs or the contributing guide), as the PR lint check is itself failing.

2023-02-10 07:39 UTC, jagpreetsinghsasan commented
If you have any issue updating the same, you can let us know here.

2023-02-10 07:40 UTC, jagpreetsinghsasan requested changes
Requesting correct PR title and commit message to trigger the CI (currently failing at the PR lint itself during the time of review)

2023-03-28 02:43 UTC, petermetz requested changes
@barneyshyperethers Plus one to what @jagpreetsinghsasan had said. If you struggle with git commands to make it happen you can also join the daily pair programming call [1] that we have and I'll be happy to do screen-sharing and get you through it (or just do it myself if that's easier and you don't mind inviting me as a collaborator to your fork which would grant me write access)

[1] https://wiki.hyperledger.org/display/cactus/Daily+Pair+Programming+Calls

2023-08-15 23:54 UTC, petermetz commented
Closing due to inactivity. Please feel free to reopen anytime.

2023-08-15 23:54 UTC, closed without merging