chore(deps): upgrade decode-uri-component to > 0.2.2 #2243
hyperledger/cacti pull request #2296
Opened 2023-02-20 14:50 UTC by charellesandig

Fixes #2243 

Signed-off-by: charellesandig charelle.wrk@gmail.com

2023-02-23 08:26 UTC, jagpreetsinghsasan approved these changes
LGTM

2023-03-02 03:35 UTC, petermetz requested changes
@charellesandig Please remove all occurrences of the dependency not just one.

```sh
$ npm ls decode-uri-component
@hyperledger/cactus@ /home/peter/a/blockchain/cactus
├─┬ @hyperledger/cactus-cmd-socketio-server@1.1.3 -> ./packages/cactus-cmd-socketio-server
│ └─┬ web3@1.8.2
│   └─┬ web3-bzz@1.8.2
│     └─┬ swarm-js@0.1.40
│       └─┬ xhr-request@1.1.0
│         └─┬ query-string@5.1.1
│           └── decode-uri-component@0.2.2 deduped
├─┬ @hyperledger/cactus-example-supply-chain-frontend@1.1.3 -> ./examples/cactus-example-supply-chain-frontend
│ └─┬ @angular-devkit/build-angular@13.3.5
│   └─┬ stylus@0.56.0
│     └─┬ css@3.0.0
│       └─┬ source-map-resolve@0.6.0
│         └── decode-uri-component@0.2.2 deduped
└─┬ @hyperledger/cactus-test-tooling@1.1.3 -> ./packages/cactus-test-tooling
  └─┬ keycloak-admin@1.14.22
    └─┬ query-string@6.14.1
      └── decode-uri-component@0.2.2

```

2023-03-08 05:28 UTC, charellesandig commented
Hi @petermetz ,  for these packages I upgraded the direct dependencies where `decode-uri-component` occurs.

```
packages/cactus-cmd-socketio-server
packages/cactus-cmd-socketio-server
cactus-test-tooling
cactus-verifier-client
```

For `cactus-verifier-client` when I upgraded from "jest-extended": "0.11.5" to "jest-extended": "3.0.1" the `docode-uri-component` is not present anymore.

2023-04-11 13:56 UTC, charellesandig commented on examples/cactus-example-carbon-accounting-frontend/package.json
> +    "@angular-devkit/build-angular": "15.2.4",
Hi @petermetz , running `yarn build:dev` on this branch is not giving successful results. I also tried running it without my changes and it still fails. The error comes from `examples/cactus-workshop-examples-2022-11-14`.

2023-04-12 06:48 UTC, charellesandig commented on examples/cactus-example-carbon-accounting-frontend/package.json
> +    "@angular-devkit/build-angular": "15.2.4",
Noted on this @petermetz , I will monitor and run test once it is resolved. Thank you!

2023-04-12 07:26 UTC, charellesandig commented
Depends on: #2357

2023-07-24 21:34 UTC, petermetz approved these changes
LGTM

2023-07-24 21:34 UTC, petermetz requested changes
Can't merge until maintainer consensus has been achieved.

2023-08-07 04:10 UTC, izuru0 approved these changes

2023-08-15 23:53 UTC, petermetz approved these changes
I rebased onto upstream/main, fixed the merge conflicts and in the meantime Izuru reviewed it too, so we are good to go.

2023-08-17 05:57 UTC, merged