fix(iroha2-connector): fix flaky tests
hyperledger/cacti pull request #2381
Opened 2023-04-07 13:19 UTC by outSH

- Use waitForCommit for all transactions used in test suites to prevent spurious CI test failures.

Closes: #2370
Closes: #2373

2023-04-07 15:48 UTC, petermetz approved these changes
@outSH LGTM just please try to make the commit subject a little more unique. If neither of the file paths of the test cases fit in the subject because they are too long for the linter then I would at least include the two issue numbers in the subject as well just so that it's easy to distinguish this commit from the other commits in the future that will do the same thing (flaky tests are something that always comes up even if we disappear all of them at once new race conditions get added all the time)

2023-04-11 04:54 UTC, jagpreetsinghsasan approved these changes

2023-04-11 09:45 UTC, outSH commented
> @outSH LGTM just please try to make the commit subject a little more unique. If neither of the file paths of the test cases fit in the subject because they are too long for the linter then I would at least include the two issue numbers in the subject as well just so that it's easy to distinguish this commit from the other commits in the future that will do the same thing (flaky tests are something that always comes up even if we disappear all of them at once new race conditions get added all the time)

@petermetz Sure thing, done :)

2023-04-12 00:14 UTC, petermetz requested changes
Dummy change request so that we don't accidentally merge this before the other orgs approval.

2023-04-26 06:36 UTC, sandeepnRES approved these changes
LGTM

2023-05-04 06:28 UTC, merged