Added azure-container-scan.yaml file
hyperledger/cacti pull request #2437
Opened 2023-05-24 06:55 UTC by adrianbatuto

2023-06-14 19:45 UTC, petermetz requested changes
@adrianbatuto Thank you! Please do the following and then pass it back for re-review:
1. Confirm that the new image is functioning well via locally executed manual testing:
1.1. build the image locally, 
1.2. modify one of the test cases to use said local image
1.3. run the test case against the locally built image
1.4. post here the steps you took to do all the above, the exact path to the test case and the complete logs the test case produced while using the image
2. Explain how did you verify that the vulnerabilities are fixed by the change you just made (e.g. did you re-run the scan locally and it showed the warnings missing or something?)
3. Remove the azure-container-scan.yaml file from the diff, we can add the container scanning in another PR (I think there was another task+PR for it already too)

2023-08-03 07:14 UTC, jagpreetsinghsasan commented
@adrianbatuto any updates on this?

2023-08-07 08:02 UTC, adrianbatuto commented
> @adrianbatuto any updates on this?

Hi @jagpreetsinghsasan , currently looking into this and following Peter's instructions.

2023-09-29 20:22 UTC, petermetz commented
Closing this for now, let's re-open it once it's ready to be reviewed.

2023-09-29 20:22 UTC, closed without merging