refactor(plugin-htlc-eth-besu): stop using the deprecated api.encodePacked
hyperledger/cacti pull request #2538
Opened 2023-07-06 05:35 UTC by RafaelAPB

1. Add tests to vanilla HashTimeLock
2. Replace abi.encodePacked by abi.encode
3. Compile and replace generated ABIs (for HashTimeLock and PrivateHashTimeLock)

Addresses #2531 
cc @petermetz

2023-07-06 19:11 UTC, petermetz requested changes
@RafaelAPB LGTM but could you please recompile the contracts with https://marketplace.visualstudio.com/items?itemName=JuanBlanco.solidity so that the .json artifacts structure is not changed at the same time?

2023-07-18 00:26 UTC, petermetz approved these changes

2023-07-18 03:13 UTC, jagpreetsinghsasan commented
LGTM (Peter has already approved to not approving it, as we need 3 approvals from different orgs)

2023-07-24 09:06 UTC, merged

2023-07-25 22:43 UTC, RafaelAPB commented
@petermetz thank you for updating the contracts!