feat(cactus-plugin-ledger-connector-ethereum): support London fork gas prices
hyperledger/cacti pull request #2630
Opened 2023-08-21 15:38 UTC by outSH

- Add legacy and EIP1559 gas configuration options to transaction requests.
- Legacy gas configuration is updated to EIP1559 using the same logic as web3 libraries.
- Update the tests to work with new API.
- Added test suite to test new features - `geth-transact-and-gas-fees.test.ts`

Depends on #2581

Signed-off-by: Michal Bajer <michal.bajer@fujitsu.com>

2023-08-25 07:05 UTC, petermetz approved these changes
LGTM

2023-08-29 03:57 UTC, izuru0 approved these changes
LGTM

2023-09-08 02:04 UTC, petermetz requested changes
@outSH Please resolve the merge conflicts, rebase, squash as needed, etc and then pass it back for review!

2023-10-02 10:36 UTC, outSH commented on packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/plugin-ledger-connector-ethereum.ts
> +    return looseWeb3Eth[args.methodName](...web3MethodArgs);
Leftover from dependency commit - false positive

2023-10-02 10:36 UTC, outSH commented on packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/plugin-ledger-connector-ethereum.ts
> +    const method = methodRef(...req.params);
Leftover from dependency commit - false positive

2023-10-02 10:36 UTC, outSH commented on packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/plugin-ledger-connector-ethereum.ts
> +    return methodRef(...contractMethodArgs)[args.invocationType](
Leftover from dependency commit - false positive

2023-10-02 23:00 UTC, petermetz approved these changes

2023-10-02 23:03 UTC, merged