Fix deprecation of deb.nodesource.com/setup_16.x
hyperledger/cacti pull request #2706
Opened 2023-09-18 07:22 UTC by urvish667

**Change Description:**

In the Dockerfile, the issue related to NodeJS was addressed by updating the NodeJS installation method to use the new NodeSource installation method. The previous method using `curl -sL https://deb.nodesource.com/setup_16.x | bash -` had become deprecated, so the new method was applied for compatibility with the latest practices.

The specific changes made in the Dockerfile are as follows:

1. Removed the old installation method for NodeJS:

   ```Dockerfile
   # Removed the deprecated NodeJS installation method
   # RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
   ```

2. Added the new NodeSource installation method:

   ```Dockerfile
   # Added the new NodeSource installation method for NodeJS
   RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /usr/share/keyrings/nodesource-archive-keyring.gpg \
       && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/nodesource-archive-keyring.gpg] https://deb.nodesource.com/node bionic main" | tee /etc/apt/sources.list.d/nodesource.list
   ```

2023-09-18 10:43 UTC, takeutak approved these changes

2023-09-19 05:23 UTC, sandeepnRES approved these changes

2023-09-19 15:20 UTC, petermetz requested changes
@urvish667 LGTM on the diff but please make sure your commit message is the same as your PR description + title, e.g. the git commit message should be what I pasted below.

(Note that I renamed the PR title to match the issue title that you've been working on fixing)

If you need any help with git, just let me know (and invite me as a collaborator to your fork)

```sh
build(tools/docker/indy-sdk-cli): fix deprecation deb.nodesource.com/setup_16.x

**Change Description:**

In the Dockerfile, the issue related to NodeJS was addressed by updating the NodeJS installation method to use the new NodeSource installation method. The previous method using `curl -sL https://deb.nodesource.com/setup_16.x | bash -` had become deprecated, so the new method was applied for compatibility with the latest practices.

The specific changes made in the Dockerfile are as follows:

1. Removed the old installation method for NodeJS:

   ```Dockerfile
   # Removed the deprecated NodeJS installation method
   # RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
   ```

2. Added the new NodeSource installation method:

   ```Dockerfile
   # Added the new NodeSource installation method for NodeJS
   RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /usr/share/keyrings/nodesource-archive-keyring.gpg \
       && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/nodesource-archive-keyring.gpg] https://deb.nodesource.com/node bionic main" | tee /etc/apt/sources.list.d/nodesource.list
   ```

Fixes #2701  
```

2023-09-26 03:32 UTC, jagpreetsinghsasan commented
LGTM

2023-10-05 21:46 UTC, petermetz commented
@urvish667 Just checking in, are you still working on this one?

2023-10-06 06:23 UTC, petermetz commented
> @petermetz Thanks for the correction on the PR message and commit. I am still new to opensource contributions, so please tell me where I went wrong in PR.

@urvish667 No worries! Well, you haven't done anything wrong, because the contributing guide does not call out explicitly that the commit message and the PR description should match (which is an error my part).

> You already corrected PR and commit issue right? Thanks.

Not yet, but I can do it very quickly if you invite me as a collaborator to your cacti fork (it will give me permission to force push changes onto your feature branch that is backing your PR)

2023-10-06 06:23 UTC, petermetz requested changes
See my comment above^^

2023-10-06 06:29 UTC, urvish667 commented
Thanks
@petermetz, I have invited you as a collaborator in my repository.

2023-10-13 06:18 UTC, petermetz approved these changes
@urvish667 I updated your commit message, we are good to go.

2023-10-13 06:20 UTC, urvish667 commented
Thanks @petermetz

2023-10-13 06:21 UTC, merged