fix(connector-besu): toBuffer only supports 0x-prefixed hex was given…
hyperledger/cacti pull request #2831
Opened 2023-10-25 03:45 UTC by ruzell22

…: 3000000

fixes: #2791

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

2023-10-25 03:47 UTC, ruzell22 commented
24 tests successfully ran and passed on `./packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/private-deploy-contract-from-json-web3-eea.test.ts` after changing the 3000000 to its hex equivalent

![image](https://github.com/hyperledger/cacti/assets/89818529/3d5a384d-a269-4b71-96c2-52bc8fe3fbcf)

2023-11-04 03:40 UTC, petermetz requested changes
@ruzell22 The test case fails on my machine when I'm testing it (the ESM Module resolution problem)
Did you forget to push your changes by any chance?

2023-11-07 03:28 UTC, ruzell22 commented
Hello @petermetz , I have tried with a fresh clone of cactus and retested (successful) and repushed the changes as well. Let me know if it works on your end as well, thank you.

2023-12-08 02:07 UTC, petermetz commented
> Hello @petermetz , I have tried with a fresh clone of the repository and retested (successful) and repushed the changes as well. Let me know if it works on your end as well, thank you.

@ruzell22 Next time please re-request the review so that it pop ups on my list of "waiting for your review" pull requests.

2023-12-08 09:49 UTC, outSH approved these changes

2023-12-10 05:09 UTC, merged