docs(examples/cbdc): fix mismatch of fabric identities
hyperledger/cacti pull request #2912
Opened 2023-11-30 19:03 UTC by AndreAugusto11

* What I believe has been an update to the Fabric SDK has led the application to break due to having the Fabric identities hardcoded (for the Fabric-Ethereum ID mapping). This was first noted in #2739.
* An initial fix was deployed in #2802 but only the Mint function was changed, which caused other functions to be breaking at the moment (e.g., Escrow)
* This commit changes the crypto material files and reverts the workaround in PR #2802
* The crypto material is only used for testing and to show information in the frontend (e.g., requesting the balance of a specific user based on the identity)
* For critical operations, access control is being performed by the chaincode by using the call at the begining of the relevant methods

2023-12-02 00:49 UTC, petermetz requested changes
@AndreAugusto11 LGTM on the big picture. Please do the following though:
1. Delete the package-lock.json - it is redundant with the yarn.lock file
2. Update the commit message to contain all the information that you also put in the PR description - I noticed that the `Fixes #????` declaration is missing from the commit message. Other stuff might be missing too, didn't check too thoroughly

2023-12-02 02:25 UTC, AndreAugusto11 commented
> @AndreAugusto11 LGTM on the big picture. Please do the following though:
> 
> 1. Delete the package-lock.json - it is redundant with the yarn.lock file
> 2. Update the commit message to contain all the information that you also put in the PR description - I noticed that the `Fixes #????` declaration is missing from the commit message. Other stuff might be missing too, didn't check too thoroughly

Done, thank you!

2023-12-02 20:29 UTC, petermetz requested changes
@AndreAugusto11 Thank you for the updates! Sorry to just come up with this one, but there's also the issue that the GUI is crashing when I try to test it locally (not with the GUI container image):

![image](https://github.com/hyperledger/cacti/assets/1583231/45d16d0b-614f-416e-b65e-d15803e2e3d2)

2023-12-05 02:11 UTC, petermetz approved these changes

2023-12-05 03:00 UTC, izuru0 approved these changes
LGTM

2023-12-05 03:16 UTC, merged