tools(connector-fabric): address CVEs: CVE-2022-21190, CVE-2021-3918
hyperledger/cacti pull request #2967
Opened 2024-01-03 06:19 UTC by adrianbatuto

Updated the version of the api server used in the docker file.

Fixes #2864

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

2024-01-04 06:34 UTC, jagpreetsinghsasan commented
@adrianbatuto please fix the commit and PR lint failing

2024-01-15 05:31 UTC, jagpreetsinghsasan commented
@adrianbatuto the `Commit Lint` is still failing can you please check on that?

2024-01-15 05:32 UTC, jagpreetsinghsasan commented
You can refer to this PR for reference: https://github.com/hyperledger/cacti/pull/2818

2024-01-19 17:42 UTC, petermetz requested changes
@adrianbatuto  ^^ +1 to what @jagpreetsinghsasan commented

2024-01-24 06:17 UTC, sandeepnRES approved these changes

2024-01-25 21:07 UTC, petermetz commented
@adrianbatuto Next time please re-request review otherwise it won't pop up in my review queue.

2024-01-25 21:08 UTC, petermetz commented
@adrianbatuto Next time please re-request review otherwise it won't pop up in my review queue.

2024-01-25 21:08 UTC, petermetz approved these changes

2024-01-25 21:15 UTC, merged