refactor(gui): gui framework change from solid to react
hyperledger/cacti pull request #3028
Opened 2024-02-20 13:36 UTC by rwat17

- changed gui framework to react

2024-02-21 17:18 UTC, petermetz reviewed
@rwat17 LGTM with comments: I'd love some documentation why was this a net positive change. I'm guessing you find it easier to develop against react than solid, but still, if there were specific pain points that this addressed it would be good to list them both in the PR description and the **commit message as well**. 

The core idea behind this is that people who come on board to contribute to/maintain the project years from now will get useful context/knowledge from reading the wisdom we leave behind (and have none of that if we don't take time to document our choices and reasoning behind them)

2024-02-22 09:15 UTC, rwat17 commented
@petermetz Yes, the point of changing is that React is more common among people. It will be easier to develop the package for newcomers too because imo React has that advantage over Solid it is more documented/supported and more people tend to know it.

2024-02-22 12:26 UTC, outSH requested changes

2024-02-22 12:26 UTC, outSH commented on packages/cacti-ledger-browser-react/package.json
> +    "@emotion/react": "^11.11.3",
pin package versions

2024-02-22 12:26 UTC, outSH commented on packages/cacti-ledger-browser-react/package.json
> +    "@emotion/react": "^11.11.3",
remove vite and react svg

2024-02-22 13:10 UTC, rwat17 commented on packages/cacti-ledger-browser-react/src/pages/fabric/DashFabric/DashFabric.tsx
> +import styles from "./DashFabric.module.css";
Removed. They were used in Solid version, idk exactly for what reason, 0 errors after build.

2024-02-24 02:20 UTC, petermetz approved these changes
@rwat17 Thank you!

2024-02-24 02:27 UTC, merged