fix(ci): DeprecationWarning in yarn_custom_checks
hyperledger/cacti pull request #3309
Opened 2024-06-11 09:40 UTC by aldousalvarez

### **Commit** to be reviewed
---
fix(ci): DeprecationWarning in yarn_custom_checks

```
Primary Changes
----------------
1. Updated the main field to use index.js to fix the Deprecation Warning
```
Fixes #2956

**Pull Request Requirements**
- [x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [x] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [x] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [x] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

2024-06-12 21:37 UTC, petermetz requested changes
@aldousalvarez

Could you please try to create yarn patches for the affected dependencies? https://yarnpkg.com/cli/patch

For example I manually edited this file:

`examples/cactus-example-carbon-accounting-frontend/node_modules/@ionic-native/status-bar/package.json`

By replacing this

```json
"main":"bundle.js",
```

with this:

```json
"main":"./ngx/bundle.js",
```

And the warning went away, so I'm thinking if you created yarn patches for all the ones with the warnings then we could get it done all the way through.

2024-06-18 13:33 UTC, aldousalvarez commented
> @aldousalvarez
> 
> Could you please try to create yarn patches for the affected dependencies? https://yarnpkg.com/cli/patch
> 
> For example I manually edited this file:
> 
> `examples/cactus-example-carbon-accounting-frontend/node_modules/@ionic-native/status-bar/package.json`
> 
> By replacing this
> 
> ```json
> "main":"bundle.js",
> ```
> 
> with this:
> 
> ```json
> "main":"./ngx/bundle.js",
> ```
> 
> And the warning went away, so I'm thinking if you created yarn patches for all the ones with the warnings then we could get it done all the way through.

@petermetz I have tried using the yarn patches and it worked but when I try to run yarn run configure I get this

```lerna-lite notice cli v3.1.0
lerna-lite ERR! Error: Unsupported URL Type "patch:": patch:@ionic-native/splash-screen@npm%3A5.36.0#~/.yarn/patches/@ionic-native-splash-screen-npm-5.36.0-531cbbe0f8.patch
lerna-lite ERR!     at unsupportedURLType (/home/dous/cactus/node_modules/npm-package-arg/lib/npa.js:310:15)
lerna-lite ERR!     at fromURL (/home/dous/cactus/node_modules/npm-package-arg/lib/npa.js:367:13)
lerna-lite ERR!     at Function.resolve (/home/dous/cactus/node_modules/npm-package-arg/lib/npa.js:83:12)
lerna-lite ERR!     at file:///home/dous/cactus/node_modules/@lerna-lite/core/dist/package-graph/package-graph.js:45:38
lerna-lite ERR!     at Array.forEach (<anonymous>)
lerna-lite ERR!     at file:///home/dous/cactus/node_modules/@lerna-lite/core/dist/package-graph/package-graph.js:30:44
lerna-lite ERR!     at PackageGraph.forEach (<anonymous>)
lerna-lite ERR!     at new PackageGraph (file:///home/dous/cactus/node_modules/@lerna-lite/core/dist/package-graph/package-graph.js:26:14)
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^
            
Error: Unsupported URL Type "patch:": patch:@ionic-native/splash-screen@npm%3A5.36.0#~/.yarn/patches/@ionic-native-splash-screen-npm-5.36.0-531cbbe0f8.patch
    at unsupportedURLType (/home/dous/cactus/node_modules/npm-package-arg/lib/npa.js:310:15)
    at fromURL (/home/dous/cactus/node_modules/npm-package-arg/lib/npa.js:367:13)
    at Function.resolve (/home/dous/cactus/node_modules/npm-package-arg/lib/npa.js:83:12)
    at file:///home/dous/cactus/node_modules/@lerna-lite/core/dist/package-graph/package-graph.js:45:38
    at Array.forEach (<anonymous>)
    at file:///home/dous/cactus/node_modules/@lerna-lite/core/dist/package-graph/package-graph.js:30:44
    at PackageGraph.forEach (<anonymous>)
    at new PackageGraph (file:///home/dous/cactus/node_modules/@lerna-lite/core/dist/package-graph/package-graph.js:26:14)
    at file:///home/dous/cactus/node_modules/@lerna-lite/core/dist/command.js:187:37 {
  code: 'EUNSUPPORTEDPROTOCOL'
}

Node.js v20.11.1
ERROR: "build:dev:backend:postbuild" exited with 1.

2024-07-04 00:48 UTC, petermetz approved these changes
@aldousalvarez Alright, I investigated this a little further and it's going to need a bigger change in a different PR so for now let's just merge this as-is and I'll send another with the rest of the warnings. LGTM, thank you!

2024-07-05 10:50 UTC, outSH approved these changes

2024-07-05 20:11 UTC, merged