docs(build): add text build steps for Linux, Mac
hyperledger/cacti pull request #3421
Opened 2024-07-18 07:13 UTC by ashnashahgrover

and Windows

Primary Changes
----------------
1. Updated BUILD.md to include Mac OS specific
installation instructions.

Fixes #1963

Signed-off-by: ashnashahgrover <as19@williams.edu>

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

2024-07-18 07:30 UTC, jagpreetsinghsasan submitted a review, later dismissed
Need doc formatting and specifics like `installing go` page should be updated, `nvm installation` steps, etc

2024-07-21 16:57 UTC, petermetz requested changes
@ashnashahgrover Looking good, just a few nit-picks: 
1. Change the commit message and PR title to reflect the contents a little closer:
You added instructions for Mac and placeholders for Linux, Windows. Someone reading this commit message would most likely end up thinking that they are about to read the instructions on how to set the project up on Linux and the get greeted by disappointment [1].
2. Explicitly clarify if you are talking about intel or ARM macs unless you've tested the steps on both CPU architectures. If you did test it both and it works that's awesome and we should make sure that it's explicitly stated as well.


[1]:
```markdown
### Linux 
* Insert Linux instructions here 
```

2024-07-23 00:01 UTC, petermetz approved these changes

2024-07-23 03:20 UTC, jagpreetsinghsasan commented
LGTM too

2024-07-23 08:57 UTC, outSH approved these changes

2024-07-31 16:21 UTC, merged