fix(test-tooling): use of hardcoded password
hyperledger/cacti pull request #3428
Opened 2024-07-22 14:29 UTC by ashnashahgrover

### **Commit** to be reviewed
---
fix(test-tooling): use of hardcoded password

```
Primary Changes
----------------
1. Updated line 236 in openethereum-test-ledger.ts so the default password argument to the newEthPersonalAccount function is not hardcoded.
```

Fixes #2766

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

2024-07-23 03:22 UTC, jagpreetsinghsasan requested changes
Did you verify if the test cases requiring this piece of code clearly specifies `test` as the password?

2024-07-23 15:15 UTC, ashnashahgrover commented
> Did you verify if the test cases requiring this piece of code clearly specifies `test` as the password?

@jagpreetsinghsasan There are no test cases in the repo using this code/function

2024-07-31 15:56 UTC, petermetz requested changes
@ashnashahgrover Please fix the commit lint issues and document that it's a breaking change in the commit message (which then will get recognized by the change log and put in the release notes).
You can find the expected format for  breaking changes in the conventional commit messages standard.

2024-08-05 03:41 UTC, ashnashahgrover commented
> @ashnashahgrover Please fix the commit lint issues and document that it's a breaking change in the commit message (which then will get recognized by the change log and put in the release notes). You can find the expected format for breaking changes in the conventional commit messages standard.

@petermetz I have addressed these changes.

2024-08-09 16:56 UTC, petermetz requested changes
@ashnashahgrover The breaking change is that you made a previously optional parameter of the function mandatory. It doesn't refer to line breaks in text (although those can be important too because the commit linter will fail that as well).
Please refactor the PR description/commit message accordingly.

2024-08-11 21:23 UTC, ashnashahgrover commented
> @ashnashahgrover The breaking change is that you made a previously optional parameter of the function mandatory. It doesn't refer to line breaks in text (although those can be important too because the commit linter will fail that as well). Please refactor the PR description/commit message accordingly.

Have adjusted both the commit message and PR description accordingly.

2024-08-12 05:35 UTC, jagpreetsinghsasan commented
> > @ashnashahgrover The breaking change is that you made a previously optional parameter of the function mandatory. It doesn't refer to line breaks in text (although those can be important too because the commit linter will fail that as well). Please refactor the PR description/commit message accordingly.
> 
> Have adjusted both the commit message and PR description accordingly.

No it isn't updated @ashnashahgrover 

`CURRENT PR BODY` (Breaking changes going out of the primary changes section)
![image](https://github.com/user-attachments/assets/3fb6f6f5-bb2e-47cc-b7f8-d45125b2399f)

`CURRENT COMMIT MESSAGE` (Breaking changes are after the fixes tag)
![image](https://github.com/user-attachments/assets/65dcb4c0-b45b-4907-8772-2be6f2bdec26)

2024-08-12 21:51 UTC, petermetz requested changes
@ashnashahgrover I would recommend just copy pasting the commit message to the PR description so that it's a definite match character by character and see if that fixes the PR commit parity check. You can better see the differences if you open them up next to each other on two separate browser windows like this:

![image](https://github.com/user-attachments/assets/0b013bba-e924-4a5e-9c94-b369dcaea08d)

2024-08-30 01:07 UTC, petermetz approved these changes

2024-09-09 11:54 UTC, outSH approved these changes

2024-10-03 00:21 UTC, petermetz commented
Currently this one is stuck because of a pending change request from @jagpreetsinghsasan 

@ashnashahgrover In case you didn't re-request review from @jagpreetsinghsasan , please do that.
@jagpreetsinghsasan If there *was* a re-request review then please re-review when you get the chance so that we can move this along.

I'm not sure either way where did this one get stuck, but either which way let's get in moving!

2024-10-03 03:29 UTC, jagpreetsinghsasan approved these changes

2024-10-03 22:17 UTC, merged