ci(connector-xdai): fix docker rate limit issues with openethereum im…
hyperledger/cacti pull request #3447
Opened 2024-07-29 07:32 UTC by aldousalvarez

### **Commit** to be reviewed
---
ci(connector-xdai): fix docker rate limit issues with openethereum image pull 
```
Primary Changes
----------------
1. Migrated all the xdai connector tests to besu ledger
   images that is being pulled from ghcr
```
Fixes #3413

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

2024-07-29 08:53 UTC, outSH approved these changes

2024-07-30 02:20 UTC, jagpreetsinghsasan approved these changes
LGTM

2024-07-31 15:28 UTC, petermetz requested changes
@aldousalvarez Could you please take a look at the failing xdai test cases?

2024-08-01 14:03 UTC, aldousalvarez commented
@petermetz Already found which test was causing the issue. It is now fixed and the check is now passing for xdai

2024-08-01 17:14 UTC, petermetz approved these changes
@aldousalvarez Great, thank you very much for the quick turnaround!

2024-08-01 17:57 UTC, merged