refactor: Refactor negative test cases in refund.test to use Jest assertions
hyperledger/cacti pull request #3464
Opened 2024-08-07 07:50 UTC by Deepakchowdavarapu

Refactor Negative Test Cases in refund.test.ts to Use Jest Assertions

Replaced try-catch blocks with Jest’s .rejects matcher for error scenarios
in refund.test.ts. Updated test cases to use .toMatch and .toThrow for
error assertions, improving test readability and maintainability.

Test results remain consistent, and all assertions now leverage Jest’s
built-in methods.

- Rebased onto upstream/main
- Squashed into a single commit
- Signed-off commit

BREAKING CHANGE: None

Signed-off-by: Deepakchowdavarapu deepak.23bcs10092@ms.sst.scaler.com

2024-08-07 07:53 UTC, Deepakchowdavarapu commented
@petermetz  @outSH please review this !!

2024-08-07 10:21 UTC, outSH requested changes
Thanks for the updates. In the future don't open a separate PR but contact us on discord so we can assist you with any git problems you may have :) 

I've added a single commnet and I'd like you to fix the title as mentioned in previous PR, and read the contributing guide:
- Fix the title, use the one peter proposed in related issue (https://github.com/hyperledger/cacti/issues/3457).

2024-08-07 10:21 UTC, outSH commented on extensions/cactus-plugin-htlc-coordinator-besu/src/test/typescript/integration/plugin-htlc-coordinator/refund.test.ts
> +
Fix the indentation to match the rest of the file

2024-08-07 21:19 UTC, petermetz requested changes
@Deepakchowdavarapu Plus one to everything @outSH asked for.

2024-08-07 21:19 UTC, petermetz commented on extensions/cactus-plugin-htlc-coordinator-besu/src/test/typescript/integration/plugin-htlc-coordinator/refund.test.ts
> +).rejects.toThrowErrorMatchingSnapshot();
@Deepakchowdavarapu What does this additional assertion accomplish? Is this covering some edge case scenario that the other assertion does not?

2024-10-04 01:58 UTC, petermetz commented
Closing this pull request due to inactivity, but please feel free to reopen as needed and then we can continue the review.

2024-10-04 01:58 UTC, closed without merging