test(aries): refactor jest test negative test cases
hyperledger/cacti pull request #3474
Opened 2024-08-12 18:04 UTC by ashnashahgrover

## **Commit** to be reviewed
test(aries): refactor jest test negative test cases
``` 
Primary Changes
----------------
1. Refactored all the negative test case exception assertions for
cactus-plugin-ledger-connector-aries. Removed try-catch blocks,
replaced with declarations through jest-extended's own API.
```
Fixes #3473

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

2024-08-12 23:38 UTC, petermetz approved these changes

2024-08-13 02:56 UTC, jagpreetsinghsasan commented
@ashnashahgrover the pr-commit parity checker is failing because your PR message contains a special character after `Primary Changes`
This is how it is getting rendered in my mail
![image](https://github.com/user-attachments/assets/452949c2-fe87-4c5c-b777-c030d81d2b65)

I then updated your PR message and now when I run it, it still fails as there is diff (very minute)
![image](https://github.com/user-attachments/assets/7a267e26-3272-4719-b362-a52cda2e1afd)
 
 I have updated it again and it still fails and now this is something which my upcoming patch for the CI test will fix. (Please do not spend any time on fixing the Commit Parity check)

2024-08-13 09:00 UTC, outSH requested changes
LGTM, thank you!

Please run `yarn run lint` to format sources and fix the lint CI error

2024-08-13 13:53 UTC, RafaelAPB approved these changes

2024-08-22 09:46 UTC, outSH approved these changes

2024-08-22 17:33 UTC, merged